config/routes.rb
Rails.application.routes.draw do
  get 'archivos/subir_archivos'
  post 'archivos/subir_archivos'
  get 'archivos/listar_archivos'
  post 'archivos/borrar_archivos'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "perfil#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicForAll</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless flash.empty? %>
    <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
             <% end %>
    </script>
    <% end %>
    
    
    <div class="top-bar foundation-5-top-bar">
      <div class="top-bar-title">
        <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
          <button class="menu-icon" type="button" data-toggle></button>
        </span>
        <strong>MusicForAll</strong>
      </div>
      <div id="responsive-menu">
        <div class="top-bar-left">
          <ul class="dropdown vertical medium-horizontal menu" data-responsive-menu="drilldown medium-dropdown" data-auto-height="true" data-animate-height="true">
            <li>
              <a href="#">Musica</a>
              <ul class="menu">
                <li><%= link_to 'Subir cancion', archivos_subir_archivos_path %></li>
                <li><%= link_to 'Lista de canciones', archivos_listar_archivos_path %></li>
              </ul>
            </li>
          </ul>
        </div>
      <div class="top-bar-right">
          <%if user_signed_in?%>
          <strong>Bienvenido(a) <%= link_to current_user.email,root_path%> </strong>
          <div>
          <strong><%= link_to "Cerrar sesíon", destroy_user_session_path, method: :delete%></strong>
          </div>
          <div>
          <strong><%=link_to "Editar perfil", edit_user_registration_path%></strong>
          </div>
          <%else%>
          <div>
          <strong><%=link_to "login",new_user_session_path%></strong>
          </div> 
          <div>
          <strong><%=link_to "Registrarse",new_user_registration_path%></strong>
          </div>
           
          <%end%>
      </div>
          
      </div>
    </div>






    <%= yield %>

  </body>

</html>